### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by safounder** [dashby3000/loopback-connector-twilio#1]
Hi Dennis,

Thank you for create this. Just got a question about this tool.

I set the config and run the example.js it is working. 
But just confuse how to inergate it with loopback api? 
After attach the created datasource to a model in the model-config.json
I got an error message said 'No model named Twilio'

Is there a way to create /Twilio/send API? I tried serval methods, all failed.

Thanks

**Comment by HKChefo** [comment]
I encountered the same issue. Hope someone could help us solve the problem.

**Comment by stan-ros** [comment]
Just create simple `models/twilio.json`

```
{
  "name": "Twilio"
}
```

**Comment by safounder** [comment]
Thanks
