### ISSUE TITLE
npmjs.com does not reflect latest updates

### ISSUE THREAD

**Issue by rwvandenberg** [dashby3000/loopback-connector-twilio#4]
First, thank you for your work on this project, @dashby3000. 

It appears that [npmjs.com](https://www.npmjs.com/package/loopback-connector-twilio) does not currently reflect the September 15th update by @jamilhassanspain. 

Jamil applied an important dependency update; re: commit `bdeb73a61e0d56c378221edeb0d28c9c407c4d7b` [_updating package.json to the latest version of the twilio driver 3.19.x_](https://github.com/dashby3000/loopback-connector-twilio/commit/bdeb73a61e0d56c378221edeb0d28c9c407c4d7b)

If possible, could you please update the package available via npmjs.com? Thank you!

**Comment by dashby3000** [comment]
Updated and fixed.
